### ISSUE TITLE
model_selection function has wrong model names

### ISSUE THREAD

**Issue by tcrombie** [AndersenLab/easyXpress#4]
It looks like we need to update the model_selection function to find model names from CellProfiler data in a more robust way. The names of models should not be hard coded into the model_combinations.csv

**Comment by sam-widmayer** [comment]
2/18/2020 - model combinations encoded as included data within easyXpress package, _not_ inferred from the data i.e. model1, model2, model3 for three model combinations, then user re-levels endproduct to suite experimental needs

**Comment by tcrombie** [comment]
model_selection function now finds model names from within the dataframe generated by read_data and levels them by the number of objects identified. The model names are then assigned to the generalized model names encoded in the model_select_X.csv files (X is either 2,3,4).
